version: '2'
services:
    poc-mysql:
        container_name: poc-mysql
        image: mysql:5.7.13
        # volumes:
        #     - ~/volumes/jhipster/poc/mysql/:/var/lib/mysql/
        environment:
            - MYSQL_USER=root
            - MYSQL_ALLOW_EMPTY_PASSWORD=yes
            - MYSQL_DATABASE=poc
        ports:
            - 3306:3306
        command: mysqld --lower_case_table_names=1 --skip-ssl
